# Install taskfile with
# sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/go/bin

version: "3"

env:
  K6_VERSION: v0.35.0

silent: true

tasks:
  default:
    cmds:
      - task: test

  clean:
    desc: Clean up working directory
    cmds:
      - rm -rf k6 .task node_modules

  build:
    sources:
      - "**/*.go"
    generates:
      - k6
    cmds:
      - xk6 build --with github.com/msaf1980/xk6-getenv=$(pwd)

  test:
    deps: [build]
    cmds:
      - ENV_STRING=value ENV_NUM=22 ./k6 run -e VAR_STRING=string -e VAR_NUM=33 --no-usage-report test.js
